language: node_js
sudo: false
install: true
script: npm install
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: twain.hazybits.com
  region: us-west-2
  local-dir: .
  skip_cleanup: true